### PR TITLE
Support planes with non-uniform resolution

### PR DESCRIPTION
**Pull request by msmk0**
E.g. sensors with FE-I4 readout and 250x50 um pixel size.

### CODE REVIEW

**Comment by simonspa** [comment]
Awesome, thanks a lot for the cleanup. Many of your changes I meant to implement since a while but haven't found the time.
Two suggestions before merging:

* I would rename `getFullResolution` to something like `getResolutionXY` as it is more descriptive
* wouldn't it be more consistent/logical to make the `TVectorD res` parameter of `getPoint()` a `std::pair<double, double>` so it matches the return type of `getFullResolution()`? We could of course also move to completely using `TVectorD` but I'm a bit hesitant there...

Cheers,
Simon

**Comment by simonspa** [comment]
and one more thing: I would overload `getPoint()` with the old `double res` definition in order not to break people's code.

**Comment by msmk0** [comment]
I renamed `getResolutionXY(...)` and readded `getPoint(...)` with the single resolution parameter.

I used `std::pair<...>` in the `plane` and `telescope` class since these are the interfaces for the users and it seems more convenient. The `getPoint(...)` methods provide the interface to the GBL library, which uses `TVectorD`, and are only used internally. At least that is what I understood. Maybe that clarifies your second point?

**Comment by simonspa** [comment]
Makes sense to me.

Thanks for contributing, well appreciated!

**Pull request merged**
